[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
    max = ""
  [[module.imports]]
    path = "github.com/nextapps-de/flexsearch"
  [[module.imports.mounts]]
    source = "dist/flexsearch.bundle.min.js"
    target = "assets/js/modules/flexsearch/flexsearch.bundle.min.js"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"

[params.icons]
    search = "fas magnifying-glass"

[params.navigation.search]
    enabled = true
    modal = true

[params.modules.flexsearch]
    integration = "core"
    canonifyURLs = false
    frontmatter = false
    filter = ""
    localize = true